# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /posts/:title
timezone: America/Sao_Paulo

# Setup
title: Cleiton Luiz Domazak
description: 'Database administration and related stuff, by Cleiton L. Domazak'
baseurl:     ''
url:         'http://cleitondomazak.com'

author:
  name: 'Cleiton Luiz Domazak'
  url: https://facebook.com/cleitondomazak
  email: cleitondomazak@gmail.com

exclude:
  - Gemfile
  - Gemfile.lock
  - bin

gems:
  # - jekyll-mentions
  - jemoji
  - jekyll-redirect-from

sass:
  sass_dir: _scss
  compressed: true

paginate: 3

# Custom vars
show_related_posts: true
animated: true

# Social icons
show_social_icons: true
github_username: cleitondomazak

google_analytics: UA-63859009-1
disqus_shortname: cleitondomazak
